### PR TITLE
Use ip+path as identifier for the limiter and can have differents lim…

### PR DESCRIPTION
**Pull request by amcereijo**
Use ip+path as identifier for the limiter and can have differents limiter for each path in the application.

It was a necessary feature in my case. 
Maybe you wanna add this capability

### CODE REVIEW

**Comment by StevenThuriot** [comment]
Thanks @amcereijo , cool feature! :+1:

**Comment by amcereijo** [comment]
Great! I hope see it publish in npm to update my dependency 
Thanks for the module!

**Comment by StevenThuriot** [comment]
Already pushed it! :wink: It should be available.

**Comment by amcereijo** [comment]
Great!! Thanks you!

**Pull request merged**
